server:
    port: 8989
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/sg_blog
        username: root
        password: Wang123999,.,
mybatis-plus:
    configuration:
# ??
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
global-config:
    db-config:
    logic-delete-field: delFlag
    logic-delete-value: 1
    logic-not-delete-value: 0
    id-type: auto